/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.footballauctiongame;

/**
 *
 * @author Lenovo
 */
public class JoinFrame extends javax.swing.JFrame implements ServerConnection.GameStateListener{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JoinFrame.class.getName());

    private ServerConnection connection;
    private String pendingTeamName;
    /**
     * Creates new form JoinFrame
     */
    public JoinFrame() {
        initComponents();
        txtPort.setText("5555");
    }

public JoinFrame(String prefillHost) {
        this();
        txtHost.setText(prefillHost);
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHost = new javax.swing.JTextField();
        txtPort = new javax.swing.JTextField();
        txtTeamName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnConnect = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtHost.setText("Host");

        txtPort.setText("Port");

        txtTeamName.setText("Team Name");

        txtPassword.setText("Password");

        btnConnect.setText("Press");
        btnConnect.addActionListener(this::btnConnectActionPerformed);

        lblStatus.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnConnect))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblStatus)))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConnect)
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        // TODO add your handling code here:
        String host = txtHost.getText().trim();
        String portText = txtPort.getText().trim();
        String teamName = txtTeamName.getText().trim();
        String password = new String(txtPassword.getPassword());

        if (host.isEmpty() || portText.isEmpty() || teamName.isEmpty() || password.isEmpty()) {
            lblStatus.setText("Please fill all fields.");
            return;
        }
        int port;

        try {
            port = Integer.parseInt(portText);
        } catch (NumberFormatException e) {
            lblStatus.setText("Port must be a number.");
            return;
        }

        connection = new ServerConnection(this);

        boolean connected = connection.connect(host, port);
        if (!connected) {
            lblStatus.setText("Could not reach server. Check IP/port.");
            return;
        }

        connection.startListening();
        pendingTeamName = teamName;
        connection.login(teamName, password);
        lblStatus.setText("Connecting...");
    }
    public void onStateUpdate(GameStateUpdate update) {
        // Nothing to do here — MainFrame handles state once we're logged in
    }
    public void onResponse(ServerResponse response) {

        javax.swing.SwingUtilities.invokeLater(() -> {

            if (!response.isSuccess()) {
                lblStatus.setText(response.getStatusMessage());
                return;
            }

            connection.removeListener(this);

            MainFrame frame = new MainFrame(connection, pendingTeamName);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);

            dispose();
        });
    }
    public void onDisconnected(String reason) {
        javax.swing.SwingUtilities.invokeLater(() -> lblStatus.setText(reason));
    }//GEN-LAST:event_btnConnectActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtHost;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtTeamName;
    // End of variables declaration//GEN-END:variables
}
