/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.footballauctiongame;

/**
 *
 * @author Lenovo
 */
public class MainFrame extends javax.swing.JFrame {
    private AuctionEngine engine;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame(AuctionEngine engine) {

    initComponents();

    this.engine = engine;

    refreshScreen();

}
    private void refreshScreen() {

    if (engine == null) {
        return;
    }

    if (engine.auctionFinished()) {

        jLabel16.setText("Auction Finished!");

        btnBid.setEnabled(false);

        btnPass.setEnabled(false);

        return;
    }

    Player player = engine.getCurrentPlayer();

    lblPlayerName.setText(player.getName());

    lblPosition.setText(player.getPosition());

    lblOverall.setText(String.valueOf(player.getOverall()));

    lblBasePrice.setText(String.valueOf(player.getBasePrice()));

    lblCurrentBid.setText(
            String.valueOf(engine.getCurrentBid().getAmount()));

    if (engine.getCurrentBid().getBidder() == null) {

        lblHighestBidder.setText("None");

    } else {

        lblHighestBidder.setText(
                engine.getCurrentBid().getBidder().getTeamName());

    }

    lblCurrentTurn.setText(
            engine.getCurrentTeam().getTeamName());

    jLabel16.setText("Waiting for bid...");
    updateTeams();
}
    private void updateTeams() {

    StringBuilder sb = new StringBuilder();

    for (Team team : engine.getTeams()) {

        sb.append(team.getTeamName())
          .append("\n");

        sb.append("Manager : ")
          .append(team.getManager().getName())
          .append("\n");

        sb.append("Purse : ")
          .append(team.getPurse())
          .append("\n");

        sb.append("Players : \n");

        if (team.getPlayerNames().isEmpty()) {

            sb.append("None\n");

        } else {

            sb.append(team.getPlayerNames());

        }

        sb.append("\n");
        sb.append("----------------------------------\n");

    }

    jTextArea1.setText(sb.toString());

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblOverall = new javax.swing.JLabel();
        lblBasePrice = new javax.swing.JLabel();
        lblCurrentBid = new javax.swing.JLabel();
        lblHighestBidder = new javax.swing.JLabel();
        lblCurrentTurn = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        btnBid = new javax.swing.JButton();
        btnPass = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Football Auction Game");
        setResizable(false);
        setSize(new java.awt.Dimension(900, 650));

        jLabel1.setText("Player Name:");

        jLabel2.setText("Position:");

        jLabel3.setText("Overall:");

        jLabel4.setText("Base Price:");

        jLabel5.setText("Current Bid:");

        jLabel6.setText("Highest Bidder:");

        jLabel7.setText("Current Turn:");

        lblPosition.setDisplayedMnemonic('l');
        lblPosition.setText("-");
        lblPosition.setName("lblPosition"); // NOI18N

        lblOverall.setText("-");
        lblOverall.setName("lblOverall"); // NOI18N

        lblBasePrice.setText("-");
        lblBasePrice.setName("lblBasePrice"); // NOI18N

        lblCurrentBid.setText("-");
        lblCurrentBid.setName("lblCurrentBid"); // NOI18N

        lblHighestBidder.setText("-");
        lblHighestBidder.setName("lblHighestBidder"); // NOI18N

        lblCurrentTurn.setText("-");
        lblCurrentTurn.setName("lblCurrentTurn"); // NOI18N

        lblPlayerName.setDisplayedMnemonic('l');
        lblPlayerName.setLabelFor(lblPlayerName);
        lblPlayerName.setText("-");
        lblPlayerName.setName("lblPlayerName"); // NOI18N

        btnBid.setBackground(new java.awt.Color(0, 153, 0));
        btnBid.setText("Bid");
        btnBid.setName("btnBid"); // NOI18N
        btnBid.addActionListener(this::btnBidActionPerformed);

        btnPass.setBackground(new java.awt.Color(255, 0, 0));
        btnPass.setText("Pass");
        btnPass.setName("btnPass"); // NOI18N
        btnPass.addActionListener(this::btnPassActionPerformed);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setName("txtTeams"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jLabel16.setText("Ready!!");
        jLabel16.setName("lblStatus"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Football Auction Game");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCurrentTurn)
                                    .addComponent(lblHighestBidder)
                                    .addComponent(lblCurrentBid)
                                    .addComponent(lblBasePrice)
                                    .addComponent(lblOverall)
                                    .addComponent(lblPosition)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPlayerName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPass))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblPlayerName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblPosition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblOverall))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblBasePrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblCurrentBid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblHighestBidder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblCurrentTurn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBid)
                            .addComponent(btnPass)))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(0, 18, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnBidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBidActionPerformed
        // TODO add your handling code here:
        boolean success = engine.bid();

    if (success) {

        jLabel16.setText("Bid placed successfully.");

    } else {

        jLabel16.setText("Not enough purse!");

    }

    refreshScreen();
    }//GEN-LAST:event_btnBidActionPerformed

    private void btnPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassActionPerformed
        // TODO add your handling code here:
        boolean sold = engine.pass();

    if (sold) {

        jLabel16.setText("Player sold.");

    } else {

        jLabel16.setText("Turn passed.");

    }

    refreshScreen();
    }//GEN-LAST:event_btnPassActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBid;
    private javax.swing.JButton btnPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblBasePrice;
    private javax.swing.JLabel lblCurrentBid;
    private javax.swing.JLabel lblCurrentTurn;
    private javax.swing.JLabel lblHighestBidder;
    private javax.swing.JLabel lblOverall;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblPosition;
    // End of variables declaration//GEN-END:variables
}
