/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.footballauctiongame;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class MainFrame extends javax.swing.JFrame {
    private AuctionEngine engine;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    
    public MainFrame(AuctionEngine engine) {
    initComponents();
    this.engine = engine;
    refreshScreen();
    }
    
    //shows player info
    private void refreshScreen() {
        if (engine == null) {
            return;
        }
        if (engine.auctionFinished()) {
            jLabel16.setText("Auction Finished!");
            btnBid.setEnabled(false);
            btnPass.setEnabled(false);
            btnManageTeams.setEnabled(true);
            return;
        }
        //gets players details from auction engine
        Player player = engine.getCurrentPlayer();
        lblPlayerName.setText(player.getName());
        lblPosition.setText(player.getPosition());
        lblOverall.setText(String.valueOf(player.getOverall()));
        lblBasePrice.setText(String.valueOf(player.getBasePrice()));
        lblCurrentBid.setText(String.valueOf(engine.getCurrentBid().getAmount()));
        lblCurrentBid.setForeground(new java.awt.Color(0, 153, 0));
        lblCurrentBid.setFont(lblCurrentBid.getFont().deriveFont(java.awt.Font.BOLD, 16f));
        javax.swing.Timer flashTimer = new javax.swing.Timer(500, e -> {
            lblCurrentBid.setForeground(java.awt.Color.BLACK);
        });
        flashTimer.setRepeats(false);
        flashTimer.start();
        //then responds after bid or pass
        if (engine.getCurrentBid().getBidder() == null) {
            lblHighestBidder.setText("None");
        } 
        else {
            lblHighestBidder.setText(engine.getCurrentBid().getBidder().getTeamName());
        }
        lblCurrentTurn.setText(engine.getCurrentTeam().getTeamName());
        jLabel16.setText("Waiting for bid...");
        updateTeams();
    }
    
    //shows team status on side panel
    private void updateTeams() {
        teamsPanel.removeAll();
        teamsPanel.setLayout(new javax.swing.BoxLayout(teamsPanel, javax.swing.BoxLayout.Y_AXIS));
        for (Team team : engine.getTeams()) {
            JPanel card = new JPanel(new java.awt.BorderLayout(5, 2));
            card.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createTitledBorder(team.getTeamName())));
            JLabel managerLabel = new JLabel("Manager: " + team.getManager().getName());
            card.add(managerLabel, java.awt.BorderLayout.NORTH);
            JLabel moraleLabel = new JLabel("Chemistry: " + team.getChemistry() + "   |   Fan Happiness: " + team.getFanHappiness());
            card.add(moraleLabel, java.awt.BorderLayout.SOUTH);
            double startingPurse = team.getPurse() + team.getTotalSquadValue();
            int percentLeft = startingPurse == 0 ? 0 : (int) ((team.getPurse() / startingPurse) * 100);
            javax.swing.JProgressBar purseBar = new javax.swing.JProgressBar(0, 100);
            purseBar.setValue(percentLeft);
            purseBar.setStringPainted(true);
            purseBar.setString("Purse: " + team.getPurse());
            if (percentLeft < 20) {
                purseBar.setForeground(java.awt.Color.RED);
            }
            else if (percentLeft < 50) {
                purseBar.setForeground(java.awt.Color.ORANGE);
            }
            else {
                purseBar.setForeground(new java.awt.Color(0, 153, 0));
            }
            card.add(purseBar, java.awt.BorderLayout.CENTER);
            JLabel squadLabel = new JLabel("<html>" + team.getPlayerNames().replace("\n", "<br>") + "</html>");
            card.add(squadLabel, java.awt.BorderLayout.SOUTH);
            teamsPanel.add(card);
            teamsPanel.add(javax.swing.Box.createVerticalStrut(8));
        }
        teamsPanel.revalidate();
        teamsPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblOverall = new javax.swing.JLabel();
        lblBasePrice = new javax.swing.JLabel();
        lblCurrentBid = new javax.swing.JLabel();
        lblHighestBidder = new javax.swing.JLabel();
        lblCurrentTurn = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        btnBid = new javax.swing.JButton();
        btnPass = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnManageTeams = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        teamsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Football Auction Game");
        setResizable(false);
        setSize(new java.awt.Dimension(900, 650));

        jLabel1.setText("Player Name:");

        jLabel2.setText("Position:");

        jLabel3.setText("Overall:");

        jLabel4.setText("Base Price:");

        jLabel5.setText("Current Bid:");

        jLabel6.setText("Highest Bidder:");

        jLabel7.setText("Current Turn:");

        lblPosition.setDisplayedMnemonic('l');
        lblPosition.setText("-");
        lblPosition.setName("lblPosition"); // NOI18N

        lblOverall.setText("-");
        lblOverall.setName("lblOverall"); // NOI18N

        lblBasePrice.setText("-");
        lblBasePrice.setName("lblBasePrice"); // NOI18N

        lblCurrentBid.setText("-");
        lblCurrentBid.setName("lblCurrentBid"); // NOI18N

        lblHighestBidder.setText("-");
        lblHighestBidder.setName("lblHighestBidder"); // NOI18N

        lblCurrentTurn.setText("-");
        lblCurrentTurn.setName("lblCurrentTurn"); // NOI18N

        lblPlayerName.setDisplayedMnemonic('l');
        lblPlayerName.setLabelFor(lblPlayerName);
        lblPlayerName.setText("-");
        lblPlayerName.setName("lblPlayerName"); // NOI18N

        btnBid.setBackground(new java.awt.Color(0, 153, 0));
        btnBid.setText("Bid");
        btnBid.setName("btnBid"); // NOI18N
        btnBid.addActionListener(this::btnBidActionPerformed);

        btnPass.setBackground(new java.awt.Color(255, 0, 0));
        btnPass.setText("Pass");
        btnPass.setName("btnPass"); // NOI18N
        btnPass.addActionListener(this::btnPassActionPerformed);

        jLabel16.setText("Ready!!");
        jLabel16.setName("lblStatus"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Football Auction Game");

        btnManageTeams.setText("Manage Teams");
        btnManageTeams.setEnabled(false);
        btnManageTeams.addActionListener(this::btnManageTeamsActionPerformed);

        javax.swing.GroupLayout teamsPanelLayout = new javax.swing.GroupLayout(teamsPanel);
        teamsPanel.setLayout(teamsPanelLayout);
        teamsPanelLayout.setHorizontalGroup(
            teamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );
        teamsPanelLayout.setVerticalGroup(
            teamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(teamsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel1))
                                    .addGap(77, 77, 77)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCurrentTurn)
                                        .addComponent(lblHighestBidder)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblPlayerName)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel8))
                                        .addComponent(lblCurrentBid)
                                        .addComponent(lblBasePrice)
                                        .addComponent(lblOverall)
                                        .addComponent(lblPosition)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBid)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnPass))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(btnManageTeams))
                                .addComponent(jLabel9))
                            .addGap(34, 34, 34)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageTeams)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblPlayerName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblPosition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblOverall))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblBasePrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblCurrentBid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblHighestBidder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblCurrentTurn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBid)
                            .addComponent(btnPass)))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //places bid
    private void btnBidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBidActionPerformed
        // TODO add your handling code here:
        boolean success = engine.bid();
        if (success) {
            jLabel16.setText("Bid placed successfully.");
        }
        else {
            jLabel16.setText("Not enough purse!");
        }
        refreshScreen();
    }//GEN-LAST:event_btnBidActionPerformed

    //12. passes a player
    private void btnPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassActionPerformed
        // TODO add your handling code here:
        boolean sold = engine.pass();
        if (sold) {
        jLabel16.setText("Player sold.");
        }
        else {
            jLabel16.setText("Turn passed.");
        }
    refreshScreen();
    }//GEN-LAST:event_btnPassActionPerformed

    private void btnManageTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTeamsActionPerformed
        // TODO add your handling code here:
        //goes to post auction frame
        PostAuctionFrame frame = new PostAuctionFrame(engine);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_btnManageTeamsActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBid;
    private javax.swing.JButton btnManageTeams;
    private javax.swing.JButton btnPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBasePrice;
    private javax.swing.JLabel lblCurrentBid;
    private javax.swing.JLabel lblCurrentTurn;
    private javax.swing.JLabel lblHighestBidder;
    private javax.swing.JLabel lblOverall;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JPanel teamsPanel;
    // End of variables declaration//GEN-END:variables
}
