/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.footballauctiongame;

/**
 *
 * @author Lenovo
 */
import javax.swing.*;
import java.awt.Color;
import java.awt.BorderLayout;
import java.awt.Font;

//the second screen where it shows the ongoing ayction
public class MainFrame extends javax.swing.JFrame implements ServerConnection.GameStateListener{
    private ServerConnection connection;
    private String myTeamName;
    private GameStateUpdate latestUpdate;
    
    public MainFrame(ServerConnection connection, String myTeamName) {
    initComponents();
    this.connection = connection;
        this.myTeamName = myTeamName;

        connection.addListener(this);

        jLabel7.setText("Time Left:");
        btnManageTeams.setEnabled(false);
    }
    public void onStateUpdate(GameStateUpdate update) {
        javax.swing.SwingUtilities.invokeLater(() -> refreshScreen(update));
    }
    
    public void onResponse(ServerResponse response) {
        javax.swing.SwingUtilities.invokeLater(() -> jLabel16.setText(response.getStatusMessage()));
    }

    public void onDisconnected(String reason) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            jLabel16.setText(reason);
            btnBid.setEnabled(false);
        });
    }
    
    private void refreshScreen(GameStateUpdate update) {

        latestUpdate = update;
        if (update.isAuctionFinished()) {

            lblPlayerName.setText("Auction Finished!");
            btnBid.setEnabled(false);
            btnPass.setEnabled(false);
            btnManageTeams.setEnabled(true);

            updateTeams(update.getTeams());
            return;
        }

        Player player = update.getCurrentPlayer();
        lblPlayerName.setText(player.getName());
        lblPosition.setText(player.getPosition());
        lblOverall.setText(String.valueOf(player.getOverall()));
        lblBasePrice.setText(String.valueOf(player.getBasePrice()));
        lblCurrentBid.setText(String.valueOf(update.getCurrentBidAmount()));
        lblHighestBidder.setText(update.getCurrentBidderName());
        lblCurrentTurn.setText(update.getSecondsRemaining() + "s");
        boolean isHighestBidder = myTeamName.equals(update.getCurrentBidderName());
        btnPass.setEnabled(!isHighestBidder);
        btnBid.setEnabled(!isHighestBidder);
        lblCurrentTurn.setText(update.isPaused() ? "PAUSED" : update.getSecondsRemaining() + "s");
        updateTeams(update.getTeams());
    }
    private void updateTeams(java.util.ArrayList<Team> teams) {

    teamsPanel.removeAll();
    teamsPanel.setLayout(new javax.swing.BoxLayout(teamsPanel, javax.swing.BoxLayout.Y_AXIS));

    for (Team team : teams) {

        JPanel card = new JPanel(new java.awt.BorderLayout(5, 2));
        card.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5),
                javax.swing.BorderFactory.createTitledBorder(team.getTeamName())));

        JLabel managerLabel = new JLabel("Manager: " + team.getManager().getName());
        card.add(managerLabel, java.awt.BorderLayout.NORTH);

        double startingPurse = team.getPurse() + team.getTotalSquadValue();
        int percentLeft = startingPurse == 0 ? 0
                : (int) ((team.getPurse() / startingPurse) * 100);

        javax.swing.JProgressBar purseBar = new javax.swing.JProgressBar(0, 100);
        purseBar.setValue(percentLeft);
        purseBar.setStringPainted(true);
        purseBar.setString("Purse: " + team.getPurse());

        if (percentLeft < 20) {
            purseBar.setForeground(java.awt.Color.RED);
        } else if (percentLeft < 50) {
            purseBar.setForeground(java.awt.Color.ORANGE);
        } else {
            purseBar.setForeground(new java.awt.Color(0, 153, 0));
        }

        card.add(purseBar, java.awt.BorderLayout.CENTER);

        JLabel moraleLabel = new JLabel(
                "Chemistry: " + team.getChemistry()
                + "   |   Fan Happiness: " + team.getFanHappiness());

        JLabel squadLabel = new JLabel(
                "<html>" + team.getPlayerNames().replace("\n", "<br>") + "</html>");

        JPanel southPanel = new JPanel(new java.awt.GridLayout(2, 1));
        southPanel.add(moraleLabel);
        southPanel.add(squadLabel);
        card.add(southPanel, java.awt.BorderLayout.SOUTH);

        teamsPanel.add(card);
        teamsPanel.add(javax.swing.Box.createVerticalStrut(8));
    }

    teamsPanel.revalidate();
    teamsPanel.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblOverall = new javax.swing.JLabel();
        lblBasePrice = new javax.swing.JLabel();
        lblCurrentBid = new javax.swing.JLabel();
        lblHighestBidder = new javax.swing.JLabel();
        lblCurrentTurn = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        btnBid = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnManageTeams = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        teamsPanel = new javax.swing.JPanel();
        btnPass = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Football Auction Game");
        setResizable(false);
        setSize(new java.awt.Dimension(900, 650));

        jLabel1.setText("Player Name:");

        jLabel2.setText("Position:");

        jLabel3.setText("Overall:");

        jLabel4.setText("Base Price:");

        jLabel5.setText("Current Bid:");

        jLabel6.setText("Highest Bidder:");

        jLabel7.setText("Current Turn:");

        lblPosition.setDisplayedMnemonic('l');
        lblPosition.setText("-");
        lblPosition.setName("lblPosition"); // NOI18N

        lblOverall.setText("-");
        lblOverall.setName("lblOverall"); // NOI18N

        lblBasePrice.setText("-");
        lblBasePrice.setName("lblBasePrice"); // NOI18N

        lblCurrentBid.setText("-");
        lblCurrentBid.setName("lblCurrentBid"); // NOI18N

        lblHighestBidder.setText("-");
        lblHighestBidder.setName("lblHighestBidder"); // NOI18N

        lblCurrentTurn.setText("-");
        lblCurrentTurn.setName("lblCurrentTurn"); // NOI18N

        lblPlayerName.setDisplayedMnemonic('l');
        lblPlayerName.setLabelFor(lblPlayerName);
        lblPlayerName.setText("-");
        lblPlayerName.setName("lblPlayerName"); // NOI18N

        btnBid.setBackground(new java.awt.Color(0, 153, 0));
        btnBid.setText("Bid");
        btnBid.setName("btnBid"); // NOI18N
        btnBid.addActionListener(this::btnBidActionPerformed);

        jLabel16.setText("Ready!!");
        jLabel16.setName("lblStatus"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Football Auction Game");

        btnManageTeams.setText("Manage Teams");
        btnManageTeams.setEnabled(false);
        btnManageTeams.addActionListener(this::btnManageTeamsActionPerformed);

        javax.swing.GroupLayout teamsPanelLayout = new javax.swing.GroupLayout(teamsPanel);
        teamsPanel.setLayout(teamsPanelLayout);
        teamsPanelLayout.setHorizontalGroup(
            teamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );
        teamsPanelLayout.setVerticalGroup(
            teamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(teamsPanel);

        btnPass.setBackground(new java.awt.Color(255, 51, 51));
        btnPass.setText("Pass");
        btnPass.addActionListener(this::btnPassActionPerformed);

        btnPause.setText("Pause");
        btnPause.addActionListener(this::btnPauseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnManageTeams))
                            .addComponent(jLabel9))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel1))
                                        .addGap(77, 77, 77)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCurrentTurn)
                                            .addComponent(lblHighestBidder)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPlayerName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8))
                                            .addComponent(lblCurrentBid)
                                            .addComponent(lblBasePrice)
                                            .addComponent(lblOverall)
                                            .addComponent(lblPosition)))
                                    .addComponent(btnBid)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnPass)
                                        .addGap(6, 6, 6))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageTeams)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblPlayerName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblPosition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblOverall))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblBasePrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblCurrentBid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblHighestBidder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblCurrentTurn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBid)
                            .addComponent(btnPass)))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //places bid
    private void btnBidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBidActionPerformed
        // TODO add your handling code here:
        connection.sendBid();
    }//GEN-LAST:event_btnBidActionPerformed

    //works when manage team button is pressed
    private void btnManageTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTeamsActionPerformed
        // TODO add your handling code here:
    PostAuctionFrame frame = new PostAuctionFrame(connection, myTeamName, latestUpdate);
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);
    }//GEN-LAST:event_btnManageTeamsActionPerformed

    private void btnPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassActionPerformed
        // TODO add your handling code here:
        connection.sendPass();
    }//GEN-LAST:event_btnPassActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        // TODO add your handling code here:
        connection.sendTogglePause();
    }//GEN-LAST:event_btnPauseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBid;
    private javax.swing.JButton btnManageTeams;
    private javax.swing.JButton btnPass;
    private javax.swing.JButton btnPause;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBasePrice;
    private javax.swing.JLabel lblCurrentBid;
    private javax.swing.JLabel lblCurrentTurn;
    private javax.swing.JLabel lblHighestBidder;
    private javax.swing.JLabel lblOverall;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JPanel teamsPanel;
    // End of variables declaration//GEN-END:variables
}
