/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.footballauctiongame;

/**
 *
 * @author Lenovo
 */
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
public class SetupFrame extends javax.swing.JFrame {
    private ArrayList<Team> teams = new ArrayList<>();
    private ArrayList<javax.swing.JPasswordField> passwordFields = new ArrayList<>();
    private ArrayList<JTextField> teamFields = new ArrayList<>();
    private ArrayList<JTextField> managerFields = new ArrayList<>();
    private ArrayList<JTextField> purseFields = new ArrayList<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SetupFrame.class.getName());

    // Creates new form SetupFrame
    public SetupFrame() {
        initComponents();
        //creates spinner
        spnTeams.setModel(new javax.swing.SpinnerNumberModel(2, 2, 20, 1));
        //creates team panel
        teamPanel.setLayout(new javax.swing.BoxLayout(teamPanel,javax.swing.BoxLayout.Y_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spnTeams = new javax.swing.JSpinner();
        btnCreate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        teamPanel = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Football Auction Setup");
        setBackground(new java.awt.Color(204, 255, 204));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 650));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Football Auction Game");

        jLabel2.setText("Number of teams:");

        btnCreate.setText("Create Team Fields");
        btnCreate.addActionListener(this::btnCreateActionPerformed);

        javax.swing.GroupLayout teamPanelLayout = new javax.swing.GroupLayout(teamPanel);
        teamPanel.setLayout(teamPanelLayout);
        teamPanelLayout.setHorizontalGroup(
            teamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );
        teamPanelLayout.setVerticalGroup(
            teamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(teamPanel);

        btnStart.setText("Start Auction");
        btnStart.addActionListener(this::btnStartActionPerformed);

        jLabel3.setText("Team Name");

        jLabel4.setText("Manager");

        jLabel5.setText("Purse");

        jLabel6.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addGap(211, 211, 211))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spnTeams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreate)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel6)
                                .addGap(59, 59, 59)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnTeams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStart)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //sets the number of teams
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        int numberOfTeams = (Integer) spnTeams.getValue();
        if (numberOfTeams < 2) {
            javax.swing.JOptionPane.showMessageDialog(this,"At least 2 teams are required.");
            return;
        }
        teamPanel.removeAll();
        teamFields.clear();
        managerFields.clear();
        purseFields.clear();
        passwordFields.clear();
        //sets team info
        for (int i = 1; i <= numberOfTeams; i++) {
            JTextField teamField = new JTextField();
            JTextField managerField = new JTextField();
            JTextField purseField = new JTextField();
            javax.swing.JPasswordField passwordField = new javax.swing.JPasswordField();
            teamFields.add(teamField);
            managerFields.add(managerField);
            purseFields.add(purseField);
            passwordFields.add(passwordField);
            JPanel row = new JPanel(new GridLayout(1, 4, 10, 10));
            row.add(teamField);
            row.add(managerField);
            row.add(purseField);
            row.add(passwordField);
            teamPanel.add(row);
        }
        teamPanel.revalidate();
        teamPanel.repaint();
    }//GEN-LAST:event_btnCreateActionPerformed

    //Start Auction button performed
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        teams.clear();
        for (int i = 0; i < teamFields.size(); i++) {
            String teamName = teamFields.get(i).getText().trim();
            String managerName = managerFields.get(i).getText().trim();
            String purseText = purseFields.get(i).getText().trim();
            String password = new String(passwordFields.get(i).getPassword()).trim();
            if (teamName.isEmpty() || managerName.isEmpty() || purseText.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this,"Please fill all fields.");
                return;
            }
            double purse;
            try {
                purse = Double.parseDouble(purseText);
                if (purse <= 0) {
                    throw new NumberFormatException();
                }
            } 
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,"Invalid purse for Team " + (i + 1));
                return;
            }
            teams.add(new Team(teamName,new Manager(managerName, teamName, password),purse));
        }
        //loads players from excel file
        ArrayList<Player> players = ExcelReader.loadPlayers("players.xlsx");
        if (players.isEmpty()) {
            JOptionPane.showMessageDialog(this,"No players found!");
            return;
        }
        //calls auction engine
        AuctionEngine engine = new AuctionEngine(players, teams);
        //opens mainframe
        MainFrame frame = new MainFrame(engine);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new SetupFrame().setVisible(true));
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnTeams;
    private javax.swing.JPanel teamPanel;
    // End of variables declaration//GEN-END:variables
}
